"use strict";var constants={CHANGE:"CHANGE_EVENT",LOADED_FOLDERS:"LOADED_FOLDERS",LOADED_CONTENTS:"LOADED_CONTENTS",SELECTED_ITEM_CHANGED:"SELECTED_ITEM_CHANGED",SELECTED_FOLDER_CHANGED:"SELECTED_FOLDER_CHANGED",NEW_ITEM_ADDED:"NEW_ITEM_ADDED",ITEM_DELETED:"ITEM_DELETED"};
//# sourceMappingURL=../maps/app/constants.js.map
